"""Watch List YAML auto-updater.

For each Pass/Hold ticker in a run, append (or update) a minimal entry in the
watchlist YAML so the shareholder can later expand re-entry conditions manually.

Existing rich entries (full reentry_conditions / monitoring_events from E:\\Company
previous reports) are PRESERVED — we never overwrite them. We only add new tickers
or update the `review_history` of existing ones.

Default path: E:\\Company\\ai-hedge-fund\\data\\watchlist.yaml
Override via env: JP_FORK_WATCHLIST_PATH
"""

from __future__ import annotations

import logging
import os
from datetime import date
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

_DEFAULT_WATCHLIST_PATH = Path(__file__).resolve().parent.parent.parent / "data" / "watchlist.yaml"


def _resolve_watchlist_path(path: Path | str | None = None) -> Path:
    if path is not None:
        return Path(path)
    env = os.environ.get("JP_FORK_WATCHLIST_PATH")
    if env:
        return Path(env)
    return _DEFAULT_WATCHLIST_PATH


def _load_watchlist(path: Path) -> dict:
    if not path.exists():
        return {
            "version": 1,
            "last_updated": str(date.today()),
            "watchlist": [],
        }
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as e:
        logger.error("Failed to parse %s: %s — refusing to overwrite", path, e)
        raise
    data.setdefault("version", 1)
    data.setdefault("watchlist", [])
    return data


def _signal_summary(pm_signals: list[dict]) -> str:
    """Build a short consensus string from per-PM signals."""
    if not pm_signals:
        return "no PM signals"
    bull = sum(1 for s in pm_signals if s.get("signal") == "bullish")
    bear = sum(1 for s in pm_signals if s.get("signal") == "bearish")
    neu = sum(1 for s in pm_signals if s.get("signal") == "neutral")
    return f"Bullish {bull} / Neutral {neu} / Bearish {bear}"


def _decide_status(action: str, pm_signals: list[dict]) -> str | None:
    """Map portfolio action to Watch List status string.

    Returns None when the recommendation is a clear Buy (= no watch needed).
    """
    if action in ("buy",):
        return None  # Active position, not a watch item
    if action in ("hold",):
        return "watch"
    if action in ("sell", "short", "cover"):
        # Bearish-leaning judgments go to watch as well (track for re-entry)
        return "watch"
    return "watch"


def append_or_update(
    ticker: str,
    *,
    rec_id: str,
    action: str,
    pm_signals: list[dict],
    pm_reasoning: str,
    on_date: date | None = None,
    watchlist_path: Path | str | None = None,
) -> Path:
    """Append a new Watch List entry or update review_history of an existing one.

    Returns the watchlist path on success.
    """
    status = _decide_status(action, pm_signals)
    if status is None:
        logger.info("Ticker %s is a Buy — not added to watchlist", ticker)
        # Buy: nothing to track here, return path for consistency
        return _resolve_watchlist_path(watchlist_path)

    path = _resolve_watchlist_path(watchlist_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    data = _load_watchlist(path)
    today = on_date or date.today()

    summary = _signal_summary(pm_signals)
    note = (
        f"Auto-generated by ai-hedge-fund (JP fork). "
        f"Action={action.upper()}, PM consensus={summary}. "
        f"Reasoning: {pm_reasoning[:200]}"
    )

    existing = next((e for e in data["watchlist"] if str(e.get("ticker")) == str(ticker)), None)

    if existing is None:
        new_entry: dict[str, Any] = {
            "ticker": str(ticker),
            "name": "[TBD — fill manually]",
            "status": status,
            "added_at": str(today),
            "source_recommendation_id": rec_id,
            "pm_consensus": summary,
            "reentry_conditions": "[TBD — shareholder to define per-PM re-entry rules]",
            "monitoring_events": "[TBD — populate market events to watch]",
            "next_review_due": "[TBD — typically +30 days]",
            "review_history": [
                {
                    "date": str(today),
                    "recommendation_id": rec_id,
                    "outcome": status,
                    "notes": note,
                }
            ],
        }
        data["watchlist"].append(new_entry)
        logger.info("Appended new watchlist entry for %s (status=%s)", ticker, status)
    else:
        # Update existing entry's review history; do NOT touch existing
        # reentry_conditions / monitoring_events / pm_consensus (manually curated).
        history = existing.setdefault("review_history", [])
        history.append({
            "date": str(today),
            "recommendation_id": rec_id,
            "outcome": status,
            "notes": note,
        })
        # Status: only update if currently empty
        existing.setdefault("status", status)
        logger.info("Appended history to existing watchlist entry for %s", ticker)

    data["last_updated"] = str(today)

    # Write back atomically (write to temp then rename)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, allow_unicode=True, sort_keys=False, indent=2)
    tmp.replace(path)
    return path


def update_watchlist_for_run(
    result: dict,
    *,
    tickers: list[str],
    rec_id_map: dict[str, str],
    watchlist_path: Path | str | None = None,
) -> list[Path]:
    """High-level entry: walk all tickers and update watchlist for each.

    Args:
        result: dict returned by run_hedge_fund
        tickers: list of tickers analysed
        rec_id_map: mapping {ticker: rec_id} produced by emit_reports_for_run

    Returns the list of (deduplicated) watchlist paths written to.
    """
    decisions = result.get("decisions") or {}
    signals = result.get("analyst_signals") or {}

    pm_agent_names = {
        "warren_buffett_agent", "charlie_munger_agent", "ben_graham_agent",
        "bill_ackman_agent", "michael_burry_agent", "mohnish_pabrai_agent",
        "nassim_taleb_agent", "peter_lynch_agent", "phil_fisher_agent",
        "stanley_druckenmiller_agent", "aswath_damodaran_agent",
        "rakesh_jhunjhunwala_agent", "cathie_wood_agent",
    }

    written: set[Path] = set()
    for ticker in tickers:
        dec = decisions.get(ticker, {})
        action = (dec.get("action") or "").lower()
        pm_reasoning = dec.get("reasoning", "")
        pm_signals = []
        for agent_name, ticker_map in signals.items():
            if agent_name not in pm_agent_names:
                continue
            sig = (ticker_map or {}).get(ticker)
            if sig:
                pm_signals.append(sig)
        rec_id = rec_id_map.get(ticker, "REC-UNKNOWN")
        path = append_or_update(
            ticker=ticker,
            rec_id=rec_id,
            action=action,
            pm_signals=pm_signals,
            pm_reasoning=pm_reasoning,
            watchlist_path=watchlist_path,
        )
        written.add(path)
    return list(written)
